observability_master:
  hosts:
    obs-master-01:
      ansible_host: 172.16.0.182
      

observability_agent:
  hosts:
    obs-agent-01:
       ansible_host: 192.168.50.220
       ansible_user: zulendra
       ansible_become: true
    #obs-agent-[01:09]:

    obs-agent-02:
      ansible_host: 192.168.50.235
      ansible_user: rusdianto04
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3




#all:
#  children:
#    observability_master:
#      hosts:
#        obs-master-01:
#          ansible_host: 172.16.0.182

   # observability-agent:
    #  hosts:
     #   obs-agent-01:
      #    ansible_host: 172.16.0.183
       # obs-agent-02:
        #  ansible_host: 172.16.0.184
        #obs-agent-03:
         # ansible_host: 172.16.0.185
        #obs-agent-04:
         # ansible_host: 172.16.0.186
        #obs-agent-05:
         # ansible_host: 172.16.0.187
        #obs-agent-06:
         # ansible_host: 172.16.0.188
        #obs-agent-07:
         # ansible_host: 172.16.0.189
        #obs-agent-08:
         # ansible_host: 172.16.0.190
        #obs-agent-09:
          #ansible_host: 172.16.0.191
