#servertest
#menjadi server utama untuk monitoring
observability_master:
  hosts:
    obs-master-01:
      ansible_host: 172.16.0.182
      ansible_user: sysadmin
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

observability_agent:
  hosts:
    obs-agent-01:
       ansible_host: 192.168.51.93
       ansible_user: rusdianto04
       ansible_become: true
       ansible_python_interpreter: /usr/bin/python3
    #obs-agent-[01:09]:

#official site
    obs-agent-02:
      ansible_host: 172.16.0.45
      ansible_user: sysadmin
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

#odelia jurnal
    obs-agent-03:
      ansible_host: 172.16.0.46
      ansible_user: sysadmin
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
#e-learning
    obs-agent-04:
      ansible_host: 172.16.0.18
      ansible_user: sysadmin
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
#CATC
    obs_agent-05:
      ansible_host: 172.16.0.34
      ansible_user: sysadmin
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
    #obs-agent-06:
      #ansible_host: 172.16.0.21
      #ansible_user: e-training
      #ansible_become: true
      #ansible_python_interpreter: /usr/bin/python3


#all:
#  children:
#    observability_master:
#      hosts:
#        obs-master-01:
#          ansible_host: 172.16.0.182

   # observability-agent:
    #  hosts:
     #   obs-agent-01:
      #    ansible_host: 172.16.0.183
       # obs-agent-02:
        #  ansible_host: 172.16.0.184
        #obs-agent-03:
         # ansible_host: 172.16.0.185
        #obs-agent-04:
         # ansible_host: 172.16.0.186
        #obs-agent-05:
         # ansible_host: 172.16.0.187
        #obs-agent-06:
         # ansible_host: 172.16.0.188
        #obs-agent-07:
         # ansible_host: 172.16.0.189
        #obs-agent-08:
         # ansible_host: 172.16.0.190
        #obs-agent-09:
          #ansible_host: 172.16.0.191
