- name: Create agent directory
  become: true
  file:
    path: "{{ agent_path }}"
    state: directory
    mode: '0755'

- name: Copy installation script
  become: true
  copy:
    src: installer_agent.sh
    dest: "{{ agent_path }}/installer_agent.sh"
    owner: root
    group: root
    mode: '0755'

- name: Run installation script
  become: true
  command: bash installer_agent.sh
  #shell: bash installer_agent.sh 4
  args:
    chdir: "{{ agent_path }}"



- name: Copy agent docker compose
  become: true
  copy:
    src: agent-compose/
    dest: "{{ agent_path }}/"
    owner: root
    group: root
    mode: '0755'

- name: Start agent containers
  become: true
  command: docker compose up -d
  args:
    chdir: "{{ agent_path }}"

- name: Healthcheck cAdvisor
  uri:
    url: http://localhost:8080/healthz
    status_code: 200
  register: cadvisor_health
  retries: 10
  delay: 3
  until: cadvisor_health.status == 200

# - name: Healthcheck redis
#   uri:
#     url: http://localhost:6379
#     status_code: 200
#   register: redis_health
#   retries: 10
#   delay: 3
#   until: redis_health.status == 200

- name: Healthcheck prometail
  uri:
    url: http://localhost:9080/ready
    status_code: 200
  register: promtail_health
  retries: 10
  delay: 3
  until: promtail_health.status == 200

